apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: '#{service}#-gateway'
  namespace: '#{namespace}#'
  labels:
    app.bancolombia.com.co/env: '#{env}#'
    app.bancolombia.com.co/cost-center: '#{cost-center}#'
    app.bancolombia.com.co/application-code: '#{application-code}#'
    app.bancolombia.com.co/project: '#{project-name}#'
    app.bancolombia.com.co/pmo: '#{pmo}#'
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '#{gateway-internal-host}#'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: '#{service}#-vs'
  namespace: '#{namespace}#'
  labels:
    app.bancolombia.com.co/env: '#{env}#'
    app.bancolombia.com.co/cost-center: '#{cost-center}#'
    app.bancolombia.com.co/application-code: '#{application-code}#'
    app.bancolombia.com.co/project: '#{project-name}#'
    app.bancolombia.com.co/pmo: '#{pmo}#'
spec:
  hosts:
  - '#{gateway-internal-host}#'
  gateways:
  - '#{service}#-gateway'
  http:
  - match:
    - uri:
        prefix: '#{path-prefix}#metrics'
    rewrite:
      uri: /metrics
    route:
    - destination:
        host: '#{service}#'
        port:
          number: 9568
  - match:
    - uri:
        prefix: '#{path-prefix}#'
    rewrite:
      uri: /
    route:
    - destination:
        host: '#{service}#'
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app.bancolombia.com.co/env: '#{env}#'
    app.bancolombia.com.co/cost-center: '#{cost-center}#'
    app.bancolombia.com.co/application-code: '#{application-code}#'
    app.bancolombia.com.co/project: '#{project-name}#'
    app.bancolombia.com.co/pmo: '#{pmo}#'
  name: '#{service}#-deployment-vision-vs'
  namespace: '#{namespace}#'
spec:
  gateways:
  - '#{service}#-gateway'
  hosts:
  - '#{gateway-internal-host}#'
  http:
  - match:
    - uri:
        prefix: '#{path-prefix}#actuator/prometheus'
    rewrite:
      uri: '#{path-prefix}#actuator/prometheus'
    route:
    - destination:
        host: '#{service}#'
        port:
          number: 80
